image: ruby:2.3

variables:
  JEKYLL_ENV: production

before_script:
  - bundle install
  - wget -q -P /tmp/ https://repo.continuum.io/miniconda/Miniconda3-4.3.30-Linux-x86_64.sh
  - bash /tmp/Miniconda3-4.3.30-Linux-x86_64.sh -b -p /tmp/miniconda
  - export PATH=/tmp/miniconda/bin:$PATH
  - conda install -y -q notebook

test:
  stage: test
  script:
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master

