image: ruby:2.3

variables:
  JEKYLL_ENV: production
  GIT_SUBMODULE_STRATEGY: 'recursive'

before_script:
  - bundle install
  - wget -q https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  - bash Miniconda3-latest-Linux-x86_64.sh -b -p miniconda
  - rm Miniconda3*.sh
  - export PATH=$(pwd)/miniconda/bin:$PATH
  - conda install -y -q notebook

instances:
  stage: test
  script:
    - main_dir=$(pwd)
    - conda install -y -q maven libxml2 pandas nbconvert nbformat matplotlib pytest
    - pip install beautifulsoup4
    - cd jovial
    - mvn -q package -DskipTests
    - cd ..
    - error=0
    - test="bash $(pwd)/ci/test_instances.sh"
    - export JOVIAL="java -jar $(pwd)/jovial/target/jovial-1.0-SNAPSHOT-jar-with-dependencies.jar"
    - export SCHEMA="$(pwd)/jovial/src/test/resources/VOTable-1.4.xsd"
    - cd assets/examples/cube/current/instances
    - ${test}
    - cd ../../../stc2/current/instances
    - ${test}
    - cd ${main_dir}
    - cd rama
    - python setup.py develop
    - cd ..
    - pytest ci/test_notebooks.py

jekyll:
  stage: test
  script:
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master

