# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: IVOA Data Model Examples
email: olaurino@cfa.harvard.edu
description: > # this means to ignore newlines until "baseurl:"
  This website contains example serializations for instances of IVOA Data Models. Information in this site is currently
  not sanctioned by the IVOA but it is used by Data Model Working Group members as a tool for discussing and documenting
  data models.
baseurl: "/ivoa-dm-examples" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  olaurino

# Build settings
markdown: kramdown
theme: minima

plugins:
   - jekyll-jupyter-notebook
   - jekyll-mermaid

mermaid:
  src: '/ivoa-dm-examples/js/mermaid/mermaid.min.js'

#plugins:
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
    - miniconda/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
